services:
  # 백엔드 서비스
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: mcp-backend
    volumes:
      - ../:/app/mcp
      - ../mcp_tools:/app/mcp_tools
      - ../.env:/app/.env
      - ./config.json:/app/config.json
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./files:/app/files
      - ./workflows:/app/workflows
      - ./agents:/app/agents
      - ./knowledge:/app/knowledge
      - ./backend.py:/app/backend.py
      - ./app.py:/app/app.py
      - ./multi_agent_api.py:/app/multi_agent_api.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - SSH_HOST=${SSH_HOST}
      - SSH_PORT=${SSH_PORT}
      - SSH_USERNAME=${SSH_USERNAME}
      - SSH_PASSWORD=${SSH_PASSWORD}
    restart: unless-stopped

  # Streamlit 프론트엔드 서비스
  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    container_name: mcp-streamlit
    ports:
      - '8501:8501'
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py
      - ../.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped